version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: my_mysql_db_not_secure
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_app_db_not_secure
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3300"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_backend_app_not_secure
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: mysql+mysqlconnector://user:password@mysql:3306/my_app_db_not_secure
    depends_on:
      - mysql
    volumes:
      - ./backend:/app

  frontend:
    image: nginx:1.29-alpine-perl
    container_name: my_frontend_app_not_secure
    ports:
      - "3001:80"
    volumes:
      - ./frontend:/usr/share/nginx/html